version: '2'
services:
    mysql:
        image: mariadb:10.3
        expose:
          - '3306'
        ports:
            - '3306:3306'
        volumes:
            - ./data/mysql:/var/lib/mysql
        restart: on-failure
        env_file:
            - docker.env
    nginx:
        image: nginx:1.13
        ports:
            - '80:80'
        restart: on-failure
        volumes:
            - ./docker-images/nginx-extended/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/code
    php-fpm:
        build: ./docker-images/php-extended
        restart: on-failure
        volumes:
            - ./docker-images/php-extended/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./:/code
    redis:
      image: 'bitnami/redis:latest'
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - REDIS_HOST=redis
      ports:
        - '6379:6379'
      volumes:
        - ./data/redis:/bitnami
#    mongodb:
#      image: mongo:latest
#      ports:
#        - '27017:27017'
#    elasticsearch:
#      image: elasticsearch
#      environment:
#        - cluster.name=docker-cluster
#        - bootstrap.memory_lock=true
#        - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
#      ports:
#        - '9200:9200'
    pma:
      image: 'phpmyadmin/phpmyadmin:latest'
      ports:
        - '8080:80'
      environment:
        - MYSQL_USER=docker
        - MYSQL_ROOT_PASSWORD=docker
        - PMA_HOST=mysql
    solr:
      build: ./docker-images/solr
#      image: solr:6.6
      ports:
      - "8983:8983"
      volumes:
      - ./data/solr/ap2:/opt/solr/server/solr/ap2
      - ./data/solr/uc:/opt/solr/server/solr/uc
      - ./data/solr/stock:/opt/solr/server/solr/stock